
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Nov 21 20:04:00 CST 2015
//----------------------------------------------------

package proyecto1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIAGONAL = 4;
  public static final int DOSPUNTOS = 5;
  public static final int SCANF = 30;
  public static final int PORCIENTO = 25;
  public static final int EQUALS = 8;
  public static final int FRASE = 36;
  public static final int DIFERENTE = 9;
  public static final int LLAVEDER = 19;
  public static final int INT = 21;
  public static final int PUNTOCOMA = 3;
  public static final int STDIO = 35;
  public static final int H = 34;
  public static final int FOR = 20;
  public static final int MENORIGUAL = 11;
  public static final int MENOSNUM = 12;
  public static final int CONIO = 26;
  public static final int IF = 33;
  public static final int AMPERSAND = 28;
  public static final int MASNUM = 14;
  public static final int MAYORIGUAL = 10;
  public static final int EOF = 0;
  public static final int COMILLAS = 27;
  public static final int error = 1;
  public static final int GETCH = 29;
  public static final int COMA = 2;
  public static final int MENOR = 17;
  public static final int VOID = 22;
  public static final int PRINTF = 31;
  public static final int MAYOR = 16;
  public static final int ELSE = 32;
  public static final int PUNTO = 24;
  public static final int LLAVEIZQ = 18;
  public static final int MENOSUNO = 13;
  public static final int NUMERAL = 23;
  public static final int OPEN = 6;
  public static final int MASUNO = 15;
  public static final int CLOSE = 7;
}

